replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"  # GKE Ingress Controller 사용
  annotations:
    kubernetes.io/ingress.global-static-ip-name: grosmichel-ip
    networking.gke.io/managed-certificates: grosmichel-cert
  hosts:
    - host: grosmichelus.com
      paths:
        - path: /template
          pathType: Prefix
