apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        develop: spring-boot
    spec:
      containers:
      - name: web-container
        image: jwh0722/web_v1:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /template
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
