apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
    cloud.google.com/backend-config: '{"default": "web-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: web
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
